import sys
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import roadmap as r  # noqa: E402

PR20 = r.Link(20, "https://x/pull/20")


def fixture(handoff=("Handoff", "https://x/issues/14"), prs=()):
    milestones = (
        r.Milestone(
            1,
            "M0 First",
            "First thing.",
            (
                r.Issue(1, "Done [one]", "https://x/issues/1", True, (PR20,)),
                r.Issue(2, "Todo", "https://x/issues/2", False, ()),
                r.Issue(4, "Hand closed", "https://x/issues/4", True, ()),
            ),
        ),
        r.Milestone(
            2,
            "M1 Second",
            "Second.",
            (r.Issue(3, "Waiting", "https://x/issues/3", False, ()),),
        ),
        r.Milestone(3, "M2 Nothing", "", ()),
    )
    adrs = (r.Doc("adr/0001-a.md", "Reject things"),)
    return r.Roadmap(milestones, tuple(prs), handoff, adrs)


def render(**kw):
    return r.render(fixture(**kw), "2026-01-02 03:04")


class RenderTest(unittest.TestCase):
    def test_header_and_timestamp(self):
        out = render()
        self.assertIn("Generated by tools/roadmap.py: do not edit", out)
        self.assertIn("Last updated: 2026-01-02 03:04 UTC", out)

    def test_deterministic(self):
        self.assertEqual(render(), render())

    def test_milestone_order(self):
        out = render()
        self.assertLess(out.index("M0 First"), out.index("M1 Second"))
        self.assertLess(out.index("M1 Second"), out.index("M2 Nothing"))

    def test_status_words(self):
        self.assertEqual(r.status_word(0, 0), "No issues yet")
        self.assertEqual(r.status_word(0, 3), "Not started")
        self.assertEqual(r.status_word(1, 3), "In progress")
        self.assertEqual(r.status_word(3, 3), "Done")
        out = render()
        self.assertIn("Status: In progress (2 of 3 closed)", out)
        self.assertIn("Status: Not started (0 of 1 closed)", out)

    def test_closed_issue_names_pr(self):
        out = render()
        self.assertIn(
            "- [x] Closed by [PR #20](https://x/pull/20): [#1 Done \\[one\\]](https://x/issues/1)",
            out,
        )
        self.assertIn("- [x] Closed (no PR): [#4 Hand closed]", out)

    def test_open_issue(self):
        self.assertIn("- [ ] Open: [#2 Todo](https://x/issues/2)", render())

    def test_empty_milestone(self):
        out = render()
        tail = out[out.index("### M2 Nothing") :]
        self.assertIn("Status: No issues yet (0 of 0 closed)", tail)
        self.assertIn("No issues yet.", tail)

    def test_in_flight_stages(self):
        prs = [
            r.PullRequest(5, "A", "https://x/pull/5", False, ("stage:implemented",)),
            r.PullRequest(6, "B", "https://x/pull/6", True, ("infra", "stage:reviewed")),
            r.PullRequest(7, "C", "https://x/pull/7", False, ("stage:simplified",)),
            r.PullRequest(8, "D", "https://x/pull/8", False, ("review-passed", "stage:simplified")),
            r.PullRequest(9, "E", "https://x/pull/9", False, ()),
        ]
        out = render(prs=prs)
        self.assertIn("Stage: Implemented, waiting for review", out)
        self.assertIn("(draft)\n  - Stage: Reviewed, waiting for simplify", out)
        self.assertIn("Stage: Simplified, waiting for final review", out)
        self.assertIn("[PR #8 D](https://x/pull/8)\n  - Stage: Review passed, ready to merge", out)
        self.assertIn("Stage: No stage yet", out)

    def test_no_prs(self):
        self.assertIn("Nothing in flight.", render())

    def test_links(self):
        out = render()
        self.assertIn("[Handoff](https://x/issues/14)", out)
        self.assertIn("[SPEC.md](SPEC.md)", out)
        self.assertIn("[Reject things](adr/0001-a.md)", out)

    def test_missing_handoff(self):
        self.assertIn("Session handoff: none found", render(handoff=None))


def _page(nodes, more=False):
    return {"pageInfo": {"hasNextPage": more}, "nodes": nodes}


class ParseTest(unittest.TestCase):
    def test_only_merged_prs_count_and_milestones_sorted(self):
        closed_issue = {
            "number": 1,
            "title": "t",
            "url": "u",
            "state": "CLOSED",
            "closedByPullRequestsReferences": {
                "nodes": [
                    {"number": 9, "url": "p9", "merged": False},
                    {"number": 8, "url": "p8", "merged": True},
                ]
            },
        }
        repo = {
            "milestones": _page(
                [
                    {"number": 2, "title": "b", "description": None, "issues": _page([])},
                    {"number": 1, "title": "a", "description": "d", "issues": _page([closed_issue])},
                ]
            ),
            "pullRequests": _page([]),
            "handoff": {"nodes": []},
        }
        milestones, _, handoff = r.parse_github(repo)
        self.assertEqual([m.number for m in milestones], [1, 2])
        self.assertEqual(milestones[0].issues[0].closed_by, (r.Link(8, "p8"),))
        self.assertIsNone(handoff)

    def test_truncated_page_fails_loud(self):
        repo = {
            "milestones": _page([], more=True),
            "pullRequests": _page([]),
            "handoff": {"nodes": []},
        }
        with self.assertRaises(r.RoadmapError):
            r.parse_github(repo)


if __name__ == "__main__":
    unittest.main()
