#!/usr/bin/env bash
# Usage: tools/play-setup.sh
#
# One-time (idempotent) setup of the play-test loop's out-of-repo parts, under
# ${DEEPCHARTER_HOME:-~/.local/share/deepcharter}. Conditions are from
# docs/tooling/mcpfabric-audit.md:
#
#   jars/mcpfabric-0.5.1+26.3.jar  GitHub release asset, sha256-pinned; a mismatch aborts
#   mcpfabric/                     clone pinned at tag v0.5.1 (b334491), MCP server built
#                                  with `npm ci --ignore-scripts && npm run build`
#   mcpfabric.config.json          bridge config: loopback, auth on, mode 600, written with
#                                  a JSON tool (a typo would silently reset every flag to on)
#   bin/mcpfabric-mcp              stdio launcher: reads the token from the config, execs the
#                                  server. The token never enters the repo.
#
# The clone stays outside the repo so its CLAUDE.md/AGENTS.md never load here.
# Prints the verified jar path on the last line of stdout.
set -euo pipefail

home="${DEEPCHARTER_HOME:-$HOME/.local/share/deepcharter}"
jar_name="mcpfabric-0.5.1+26.3.jar"
jar_sha256="187eb073b205056f258b41bbfdb308a00be0662918acac90aac6ef2332be479d"
jar_url="https://github.com/denfry/mcpfabric/releases/download/v0.5.1/mcpfabric-0.5.1%2B26.3.jar"
server_repo="https://github.com/denfry/mcpfabric.git"
server_commit="b334491cde23816c25aac3c9f6e329c10c7873e4"

jar="$home/jars/$jar_name"
clone="$home/mcpfabric"
config="$home/mcpfabric.config.json"
wrapper="$home/bin/mcpfabric-mcp"

die() { echo "play-setup: $*" >&2; exit 1; }
sha256_of() { shasum -a 256 "$1" | cut -d' ' -f1; }

umask 077
mkdir -p "$home/jars" "$home/bin"

# 1. Jar: download if absent, then verify. Refuse on any mismatch.
if [[ ! -f "$jar" ]]; then
  tmp="$(mktemp "$home/jars/download.XXXXXX")"
  trap 'rm -f "$tmp"' EXIT
  curl -fsSL -o "$tmp" "$jar_url" >&2
  [[ "$(sha256_of "$tmp")" == "$jar_sha256" ]] || die "downloaded jar hash mismatch, refusing to use it"
  mv "$tmp" "$jar"
  trap - EXIT
fi
[[ "$(sha256_of "$jar")" == "$jar_sha256" ]] || die "cached jar $jar does not match the pinned sha256; delete it and re-run"

# 2. MCP server: pinned clone, built without install scripts.
if [[ ! -d "$clone/.git" ]]; then
  git clone --quiet "$server_repo" "$clone" >&2
  git -C "$clone" checkout --quiet "$server_commit"
fi
[[ "$(git -C "$clone" rev-parse HEAD)" == "$server_commit" ]] || die "$clone is not at $server_commit"
if [[ ! -f "$clone/mcp-server/dist/index.js" ]]; then
  (cd "$clone/mcp-server" && npm ci --ignore-scripts >&2 && npm run build >&2)
fi

# 3. Bridge config: created once, flags set via a JSON tool.
if [[ ! -f "$config" ]]; then
  python3 -I - "$config" <<'PY'
import json, sys, uuid
cfg = {
    "host": "127.0.0.1",
    "port": 25599,
    "token": uuid.uuid4().hex,
    "requireAuth": True,
    "callTimeoutMs": 8000,
    "worldIdKey": uuid.uuid4().hex,
    "enableWorldWrite": True,
    "enableCommands": True,
    "enablePlayerControl": True,
    "enableVision": True,
}
with open(sys.argv[1], "w") as f:
    json.dump(cfg, f, indent=2)
PY
fi
chmod 600 "$config"
python3 -I - "$config" <<'PY'
import json, sys
cfg = json.load(open(sys.argv[1]))
assert cfg["host"] == "127.0.0.1" and cfg["requireAuth"] is True, "mcpfabric config violates audit condition 4"
PY

# 4. Stdio launcher. Contains no secret; reads the token at exec time.
cat > "$wrapper" <<WRAP
#!/bin/sh
# Generated by tools/play-setup.sh. Stdio transport only (audit conditions 3, 5, 6).
set -eu
export MCPFABRIC_URL=http://127.0.0.1:25599 MCPFABRIC_TRANSPORT=stdio MCPFABRIC_AGENT=0
MCPFABRIC_TOKEN="\$(plutil -extract token raw -o - "$config")"
export MCPFABRIC_TOKEN
exec node "$clone/mcp-server/dist/index.js"
WRAP
chmod 700 "$wrapper"

echo "$jar"
