from __future__ import annotations

import json
import re
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

REPO = "pkeppeler/deepcharter"
ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "docs" / "ROADMAP.md"
ADR_DIR = ROOT / "docs" / "adr"
HANDOFF_LABEL = "handoff"
# Pipeline order, earliest stage first.
STAGE_LABELS = ("stage:implemented", "stage:reviewed", "stage:simplified", "review-passed")
STAGE_WORDS = {
    "stage:implemented": "Implemented, waiting for review",
    "stage:reviewed": "Reviewed, waiting for simplify",
    "stage:simplified": "Simplified, waiting for final review",
    "review-passed": "Review passed, ready to merge",
}
NO_STAGE_WORD = "No stage yet"
CLOSE_WORDS = {"COMPLETED": "Completed", "NOT_PLANNED": "Not planned"}
PAGE = 100

QUERY = """
query($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    milestones(first: %(page)d, orderBy: {field: NUMBER, direction: ASC}) {
      pageInfo { hasNextPage }
      nodes {
        number title description
        issues(first: %(page)d, orderBy: {field: CREATED_AT, direction: ASC}) {
          pageInfo { hasNextPage }
          nodes {
            number title state stateReason url
            closedByPullRequestsReferences(first: 10, includeClosedPrs: true) {
              pageInfo { hasNextPage }
              nodes { number url merged }
            }
          }
        }
      }
    }
    pullRequests(states: OPEN, first: %(page)d, orderBy: {field: CREATED_AT, direction: ASC}) {
      pageInfo { hasNextPage }
      nodes {
        number title url isDraft
        labels(first: 20) { pageInfo { hasNextPage } nodes { name } }
        closingIssuesReferences(first: 10) { pageInfo { hasNextPage } nodes { number url } }
      }
    }
    handoff: issues(labels: ["%(handoff)s"], states: OPEN, first: 5) {
      pageInfo { hasNextPage }
      nodes { number title url }
    }
  }
}
""" % {"page": PAGE, "handoff": HANDOFF_LABEL}


@dataclass(frozen=True)
class Link:
    number: int
    url: str


@dataclass(frozen=True)
class Handoff:
    title: str
    url: str


@dataclass(frozen=True)
class Issue:
    number: int
    title: str
    url: str
    closed: bool
    close_reason: str | None  # GitHub stateReason, only for closed issues
    closed_by: tuple[Link, ...]  # merged PRs only


@dataclass(frozen=True)
class Milestone:
    number: int
    title: str
    description: str
    issues: tuple[Issue, ...]


@dataclass(frozen=True)
class PullRequest:
    number: int
    title: str
    url: str
    draft: bool
    labels: tuple[str, ...]
    closes: tuple[Link, ...]


@dataclass(frozen=True)
class Doc:
    path: str  # relative to docs/
    title: str


@dataclass(frozen=True)
class Roadmap:
    milestones: tuple[Milestone, ...]  # in milestone-number order
    pull_requests: tuple[PullRequest, ...]
    handoff: Handoff | None
    adrs: tuple[Doc, ...]


class RoadmapError(Exception):
    pass


# ---------------------------------------------------------------- rendering


def status_word(closed: int, total: int) -> str:
    if total == 0:
        return "No issues yet"
    if closed == total:
        return "Done"
    if closed == 0:
        return "Not started"
    return "In progress"


def _text(s: str) -> str:
    return " ".join(s.split()).replace("[", "\\[").replace("]", "\\]")


def _stage(labels: tuple[str, ...]) -> str:
    for label in reversed(STAGE_LABELS):
        if label in labels:
            return STAGE_WORDS[label]
    return NO_STAGE_WORD


def _render_issue(issue: Issue) -> str:
    link = f"[#{issue.number} {_text(issue.title)}]({issue.url})"
    if not issue.closed:
        return f"- [ ] Open: {link}"
    word = CLOSE_WORDS.get(issue.close_reason or "", "Closed")
    if issue.closed_by:
        prs = ", ".join(f"[PR #{p.number}]({p.url})" for p in issue.closed_by)
        return f"- [x] {word} by {prs}: {link}"
    return f"- [x] {word} (no PR): {link}"


def render(roadmap: Roadmap, updated: str) -> str:
    out = [
        "# Deep Charter roadmap",
        "",
        "Generated by tools/roadmap.py: do not edit",
        "",
        f"Last updated: {updated} UTC",
        "",
        "## Links",
        "",
    ]
    if roadmap.handoff:
        out.append(f"- Session handoff: [{_text(roadmap.handoff.title)}]({roadmap.handoff.url})")
    else:
        out.append("- Session handoff: none found")
    out.append("- Spec: [SPEC.md](SPEC.md)")
    out.append("- Decisions (ADRs):")
    for adr in roadmap.adrs:
        out.append(f"  - [{_text(adr.title)}]({adr.path})")
    out += ["", "## In flight", ""]
    if roadmap.pull_requests:
        for pr in roadmap.pull_requests:
            draft = " (draft)" if pr.draft else ""
            out.append(f"- [PR #{pr.number} {_text(pr.title)}]({pr.url}){draft}")
            out.append(f"  - Stage: {_stage(pr.labels)}")
            if pr.closes:
                issues = ", ".join(f"[#{i.number}]({i.url})" for i in pr.closes)
                out.append(f"  - Closes: {issues}")
    else:
        out.append("Nothing in flight.")
    out += ["", "## Milestones"]
    for m in roadmap.milestones:
        total = len(m.issues)
        closed = sum(1 for i in m.issues if i.closed)
        out += [
            "",
            f"### {_text(m.title)}",
            "",
            f"Status: {status_word(closed, total)} ({closed} of {total} closed)",
        ]
        if m.description.strip():
            out += ["", " ".join(m.description.split())]
        out.append("")
        if m.issues:
            out += [_render_issue(i) for i in m.issues]
        else:
            out.append("No issues yet.")
    return "\n".join(out) + "\n"


# ----------------------------------------------------------------- fetching


def gh_graphql(query: str, owner: str, name: str) -> dict:
    cmd = ["gh", "api", "graphql", "-f", f"query={query}", "-f", f"owner={owner}", "-f", f"name={name}"]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, check=False)
    except FileNotFoundError:
        raise RoadmapError("gh is not installed or not on PATH") from None
    if proc.returncode != 0:
        raise RoadmapError(f"gh failed (exit {proc.returncode}): {proc.stderr.strip()}")
    try:
        data = json.loads(proc.stdout)
    except json.JSONDecodeError as e:
        raise RoadmapError(f"gh returned invalid JSON: {e}") from None
    if data.get("errors"):
        raise RoadmapError(f"GraphQL errors: {data['errors']}")
    return data["data"]


def _require_complete(connection: dict, what: str) -> None:
    if connection["pageInfo"]["hasNextPage"]:
        raise RoadmapError(f"too many {what}: add pagination to tools/roadmap.py")


def parse_github(repository: dict, adrs: tuple[Doc, ...]) -> Roadmap:
    _require_complete(repository["milestones"], "milestones")
    _require_complete(repository["pullRequests"], "open PRs")
    _require_complete(repository["handoff"], f"open '{HANDOFF_LABEL}' issues")
    milestones = []
    for m in repository["milestones"]["nodes"]:
        _require_complete(m["issues"], f"issues in milestone {m['title']}")
        issues = []
        for i in m["issues"]["nodes"]:
            closers = i["closedByPullRequestsReferences"]
            _require_complete(closers, f"closing PRs for issue #{i['number']}")
            issues.append(
                Issue(
                    number=i["number"],
                    title=i["title"],
                    url=i["url"],
                    closed=i["state"] == "CLOSED",
                    close_reason=i["stateReason"],
                    closed_by=tuple(Link(p["number"], p["url"]) for p in closers["nodes"] if p["merged"]),
                )
            )
        milestones.append(Milestone(m["number"], m["title"], m["description"] or "", tuple(issues)))
    prs = []
    for p in repository["pullRequests"]["nodes"]:
        _require_complete(p["labels"], f"labels on PR #{p['number']}")
        _require_complete(p["closingIssuesReferences"], f"closing issues on PR #{p['number']}")
        prs.append(
            PullRequest(
                number=p["number"],
                title=p["title"],
                url=p["url"],
                draft=p["isDraft"],
                labels=tuple(sorted(label["name"] for label in p["labels"]["nodes"])),
                closes=tuple(Link(i["number"], i["url"]) for i in p["closingIssuesReferences"]["nodes"]),
            )
        )
    handoffs = repository["handoff"]["nodes"]
    if len(handoffs) > 1:
        raise RoadmapError(f"expected one open '{HANDOFF_LABEL}' issue, found {len(handoffs)}")
    handoff = Handoff(handoffs[0]["title"], handoffs[0]["url"]) if handoffs else None
    return Roadmap(tuple(sorted(milestones, key=lambda m: m.number)), tuple(prs), handoff, adrs)


def read_adrs(adr_dir: Path) -> tuple[Doc, ...]:
    docs = []
    for path in sorted(adr_dir.glob("*.md")):
        match = re.search(r"^# (.+)$", path.read_text(encoding="utf-8"), re.MULTILINE)
        if not match:
            raise RoadmapError(f"{path} has no '# ' heading")
        docs.append(Doc(f"adr/{path.name}", match.group(1).strip()))
    return tuple(docs)


def fetch() -> Roadmap:
    owner, name = REPO.split("/")
    repository = gh_graphql(QUERY, owner, name)["repository"]
    return parse_github(repository, read_adrs(ADR_DIR))


def main() -> int:
    if len(sys.argv) > 1:
        print("usage: python3 -I tools/roadmap.py (takes no arguments)", file=sys.stderr)
        return 2
    try:
        roadmap = fetch()
    except RoadmapError as e:
        print(f"roadmap.py: {e}", file=sys.stderr)
        return 1
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M")
    OUTPUT.write_text(render(roadmap, updated), encoding="utf-8")
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
