"""The reference sheet of palette and style: every palette colour, and every texture as it looks at light levels 15, 7, 3 and 0.

Light follows vanilla 26.3's lightmap (assets/minecraft/shaders/core/lightmap.fsh) for block light alone, with no sky, no ambient
colour, no tint and the default brightness setting (0.5): a texture's colour is multiplied by that grey. A glow layer is drawn
over its base at full light, as a model element with light_emission 15 renders. Blocks get all four levels; items only full light,
as the inventory shows them. The sheet's own frame and lettering are fixed colours, so a skin's sheet differs only in its art.
"""
from canvas import Canvas, Colour
from recipe import SIZE, Book

LEVELS = (15, 7, 3, 0)
SCALE = 3
CELL = SIZE * SCALE
GAP = 4
MARGIN = 8
LABEL = 116
BACKGROUND: Colour = (22, 20, 26, 255)
PANEL: Colour = (34, 31, 39, 255)
INK: Colour = (214, 206, 190, 255)
DIM: Colour = (128, 121, 112, 255)
BLOCK_COLUMNS = 2
ITEM_COLUMNS = 4
SWATCH = 10
PALETTE_COLUMNS = 3

# 3 x 5 capitals, digits and the punctuation the labels use.
FONT = {
    "A": ["010", "101", "111", "101", "101"], "B": ["110", "101", "110", "101", "110"], "C": ["011", "100", "100", "100", "011"],
    "D": ["110", "101", "101", "101", "110"], "E": ["111", "100", "110", "100", "111"], "F": ["111", "100", "110", "100", "100"],
    "G": ["011", "100", "101", "101", "011"], "H": ["101", "101", "111", "101", "101"], "I": ["111", "010", "010", "010", "111"],
    "J": ["001", "001", "001", "101", "010"], "K": ["101", "101", "110", "101", "101"], "L": ["100", "100", "100", "100", "111"],
    "M": ["101", "111", "111", "101", "101"], "N": ["110", "101", "101", "101", "101"], "O": ["010", "101", "101", "101", "010"],
    "P": ["110", "101", "110", "100", "100"], "Q": ["010", "101", "101", "110", "011"], "R": ["110", "101", "110", "101", "101"],
    "S": ["011", "100", "010", "001", "110"], "T": ["111", "010", "010", "010", "010"], "U": ["101", "101", "101", "101", "111"],
    "V": ["101", "101", "101", "101", "010"], "W": ["101", "101", "111", "111", "101"], "X": ["101", "101", "010", "101", "101"],
    "Y": ["101", "101", "010", "010", "010"], "Z": ["111", "001", "010", "100", "111"],
    "0": ["111", "101", "101", "101", "111"], "1": ["010", "110", "010", "010", "111"], "2": ["110", "001", "010", "100", "111"],
    "3": ["110", "001", "010", "001", "110"], "4": ["101", "101", "111", "001", "001"], "5": ["111", "100", "110", "001", "110"],
    "6": ["011", "100", "111", "101", "111"], "7": ["111", "001", "010", "010", "010"], "8": ["111", "101", "111", "101", "111"],
    "9": ["111", "101", "111", "001", "110"], " ": ["000"] * 5, "-": ["000", "000", "111", "000", "000"],
    "_": ["000", "000", "000", "000", "111"], ".": ["000", "000", "000", "000", "010"], ":": ["000", "010", "000", "010", "000"],
    "/": ["001", "001", "010", "100", "100"], "(": ["010", "100", "100", "100", "010"], ")": ["010", "001", "001", "001", "010"],
    ",": ["000", "000", "000", "010", "100"],
}


def brightness(level: int) -> float:
    """The lightmap's grey for a block light level, as lightmap.fsh computes it with brightness 0.5."""
    lit = level / 15
    grey = lit / (4 - 3 * lit)
    return 0.5 * grey + 0.5 * (1 - (1 - grey) ** 4)


def render(book: Book) -> Canvas:
    blocks = [key for key in book.recipes if key.startswith("block/")]
    items = [key for key in book.recipes if key.startswith("item/")]
    block_width = LABEL + len(LEVELS) * (CELL + GAP)
    block_rows = -(-len(blocks) // BLOCK_COLUMNS)
    item_rows = -(-len(items) // ITEM_COLUMNS)
    palette_rows = -(-len(_swatch_rows(book)) // PALETTE_COLUMNS)
    width = 2 * MARGIN + BLOCK_COLUMNS * block_width + (BLOCK_COLUMNS - 1) * GAP * 4
    height = (MARGIN + 14 + 10 + palette_rows * (SWATCH + 3) + 12 + 10 + block_rows * (CELL + GAP)
              + 12 + 10 + item_rows * (CELL + GAP) + MARGIN)
    out = Canvas(width, height, [list(BACKGROUND) for _ in range(width * height)])
    y = MARGIN
    _text(out, MARGIN, y, "DEEP CHARTER: PALETTE AND STYLE", INK, 2)
    y += 14
    _text(out, MARGIN, y, "PALETTE, DARK TO LIGHT. GENERATED BY TOOLS/TEXTURES/TEXGEN.PY FROM ITS PALETTE AND RECIPES", DIM, 1)
    y += 10
    y = _palette(out, book, y)
    y += 12
    header = "BLOCKS AT LIGHT " + ", ".join(str(level) for level in LEVELS) + " (GLOW LAYERS AT FULL LIGHT)"
    _text(out, MARGIN, y, header, DIM, 1)
    y += 10
    for i, key in enumerate(blocks):
        column, row = divmod(i, block_rows)
        x0 = MARGIN + column * (block_width + GAP * 4)
        y0 = y + row * (CELL + GAP)
        _text(out, x0, y0 + CELL // 2 - 2, key.removeprefix("block/").upper(), INK, 1)
        for j, level in enumerate(LEVELS):
            _cell(out, book, key, x0 + LABEL + j * (CELL + GAP), y0, brightness(level))
    y += block_rows * (CELL + GAP) + 12
    _text(out, MARGIN, y, "ITEMS AT FULL LIGHT", DIM, 1)
    y += 10
    item_width = (width - 2 * MARGIN) // ITEM_COLUMNS
    for i, key in enumerate(items):
        column, row = divmod(i, item_rows)
        x0 = MARGIN + column * item_width
        y0 = y + row * (CELL + GAP)
        _cell(out, book, key, x0, y0, 1.0)
        _text(out, x0 + CELL + GAP, y0 + CELL // 2 - 2, key.removeprefix("item/").upper(), INK, 1)
    return out


def _swatch_rows(book: Book) -> list[tuple[str, list[Colour]]]:
    palette = book.palette
    rows = [(name, [palette.colours[k] for k in keys]) for name, keys in palette.ramps.items()]
    in_ramps = {k for keys in palette.ramps.values() for k in keys}
    rows += [(name, [colour]) for name, colour in palette.colours.items() if name not in in_ramps]
    return sorted(rows)


def _palette(out: Canvas, book: Book, y: int) -> int:
    rows = _swatch_rows(book)
    per_column = -(-len(rows) // PALETTE_COLUMNS)
    column_width = (out.width - 2 * MARGIN) // PALETTE_COLUMNS
    for i, (name, colours) in enumerate(rows):
        column, row = divmod(i, per_column)
        x0 = MARGIN + column * column_width
        y0 = y + row * (SWATCH + 3)
        _text(out, x0, y0 + 2, name.upper(), INK, 1)
        for j, colour in enumerate(colours):
            _box(out, x0 + 60 + j * (SWATCH + 1), y0, SWATCH, SWATCH, colour)
    return y + per_column * (SWATCH + 3)


def _cell(out: Canvas, book: Book, key: str, x0: int, y0: int, light: float) -> None:
    """Frame 0 of the texture, scaled up, lit; a glow layer over its base (or over black when it has none) at full light."""
    _box(out, x0 - 1, y0 - 1, CELL + 2, CELL + 2, PANEL)
    recipe = book.recipes[key]
    texture = book.render(key)[0]
    if recipe.glow is None:
        base, glow = texture, None
    else:
        base, glow = (book.render(recipe.glow.over)[0] if recipe.glow.over else None), texture
    for sy in range(SIZE):
        for sx in range(SIZE):
            colour = (0, 0, 0, 255) if glow is not None and base is None else None
            if base is not None:
                r, g, b, a = base.get(sx, sy)
                if a:
                    colour = (round(r * light), round(g * light), round(b * light), 255)
            if glow is not None:
                r, g, b, a = glow.get(sx, sy)
                if a:
                    colour = (r, g, b, 255)
            if colour is not None:
                _box(out, x0 + sx * SCALE, y0 + sy * SCALE, SCALE, SCALE, colour)


def _box(out: Canvas, x0: int, y0: int, w: int, h: int, colour: Colour) -> None:
    for y in range(y0, y0 + h):
        for x in range(x0, x0 + w):
            out.put(x, y, colour)


def _text(out: Canvas, x0: int, y0: int, text: str, colour: Colour, scale: int) -> None:
    x = x0
    for ch in text:
        glyph = FONT.get(ch, FONT[" "])
        for gy, row in enumerate(glyph):
            for gx, bit in enumerate(row):
                if bit == "1":
                    _box(out, x + gx * scale, y0 + gy * scale, scale, scale, colour)
        x += 4 * scale
